### ISSUE TITLE
compilation warnings

### ISSUE THREAD

**Issue by Serg10** [RyoKosaka/HelloDrum-arduino-Library#22]
When I compile the code the arduino IDE says me a lot of this warnings...

`hellodrum.h:117:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]`

However the code works well...

It is important?it is problems of my IDE or libraries installed?

**Comment by RyoKosaka** [comment]
The warning is normal, it's happening in my environment as well.
This is a thing due to an incorrect declaration, but the code works fine.
I will fix it before the next release.
Thanks.
