### ISSUE TITLE
(There may be) a slight inaccuracy in the example codе

### ISSUE THREAD

**Issue by NinjaPanas** [RyoKosaka/HelloDrum-arduino-Library#25]
In - 
/RyoKosaka/HelloDrum-arduino-Library/blob/master/examples/MUX/muxSensing_minimalDrumKit_i2cLCD/**muxSensing_minimalDrumkit_i2cLCD.ino**

line 67 -  **ride**.settingName("TOM");

and 

/RyoKosaka/HelloDrum-arduino-Library/blob/master/examples/MUX/muxSensing_minimalDrumKit_lcdShield/**muxSensing_minimalDrumkit_lcdShield.ino**

line 96 -  **ride**.settingName("TOM");

It seems it  should be - **tom**.settingName("TOM");

I'm sorry for my broken english. And I'm a complete fool of programming. Sorry if it took your time.

**Comment by RyoKosaka** [comment]
thanks
I will fix it before the next release.

**Comment by NinjaPanas** [comment]
Thank YOU for your Lib!!!
