### ISSUE TITLE
Circuit for single piezo 

### ISSUE THREAD

**Issue by PavelShtykov** [RyoKosaka/HelloDrum-arduino-Library#28]
Is it correct to connect a single piezo through two 100K Ohm resistors? Some projects use only one 1M Ohm resistor.

Subquestion: Does the implementation with potentiometers have huge advantages?

**Comment by RyoKosaka** [comment]
A single 1MΩ resistor will also work. Slightly more sensitive. Choose whichever you like. Or make another suitable circuit.

The circuit of potentiometer version is based on YAMAHA PCY135. You can use this potentiometer to adjust the sensitivity of the piezo.
The circuit with the potentiometer at about halfway and the circuit with two 100kΩ resistors is similar.
For the sake of parts availability and simplicity of the circuit, I decided to use the circuit with two 100kΩ resistors.
But to be honest, I'm not sure if this circuit is the best choice.
