### ISSUE TITLE
Does it handles chokes ?

### ISSUE THREAD

**Issue by DarkPoubelle** [RyoKosaka/HelloDrum-arduino-Library#34]
Hi !

I just stumbled across this project and it seems amazing ! I'm converting an acoustic drum into a edrum with a friends using Myrk & GoeDrum stuff for the triggers piezo/switchs.

So my question is simple : does it handles chokes like the roland way ? If not do you think it's something i can add into the lib ? Or does it need a bigger work liek redesigning the whole lib ?

Thanks :)

**Comment by RyoKosaka** [comment]
It still works erratically, but you can use roland's 2 zone cymbals. Of course, it can also handle chalk. However, Roland's 3-zone cymbals are not supported. It is possible to use Roland's 3-zone cymbal as a 2-zone cymbal.

You can see the choke in action in this video. The cymbal in the video is a YAMAHA cymbal, but it also works with Roland cymbals.
https://www.youtube.com/watch?v=sk_8UGvjtP4

https://github.com/RyoKosaka/HelloDrum-arduino-Library/blob/master/examples/Basic/cymbal_2zone/cymbal_2zone.ino
It can be handled as shown in lines 76-82.

**Comment by DarkPoubelle** [comment]
Thanks for your fast reply :)

I'll give it a try then ! I'm free for the 3 zone + choke cymbal design, so i'll choose the one which fit the best with the actual code. If i need to go the yamaha way, i'll go the yamaha way haha
