### ISSUE TITLE
Low sensitivity improvement?

### ISSUE THREAD

**Issue by Jibeji** [RyoKosaka/HelloDrum-arduino-Library#50]
Hi,
I've tried the software with a Roland PDX-100 which works fine, but the sensitivity is really low even set at 100.
Most of ghost notes don't trigger.
I used 100 Kohms resistors on an Arduino Micro.
Is there a way to improve the sensitivity?

**Comment by davy39** [comment]
Hello,
To increase sensitivity, you have to decrease the sensitivity parameter.
For detecting gost notes, try to reduce threshold parameter.

**Comment by Jibeji** [comment]
Thank you!
