### ISSUE TITLE
Hairless Midi “Warning:got a status byte…”

### ISSUE THREAD

**Issue by Willtcs** [RyoKosaka/HelloDrum-arduino-Library#51]
Hi everyone I've been trying to make 16 channel drumset and also my circuit are using mux. I modified the code from RyoKosaka HelloDrum-arduino-Library Basic code to suit for my Arduino drum project. I use loopMIDI and hairless but I have problem with Hairless. Does that happen because of HelloDrum library or MIDI library? Can everyone help me to solve that?

![error 3](https://user-images.githubusercontent.com/115413953/194764733-e6a30ab9-4e84-4ee4-8bcf-450fc06cfe76.JPG)
every time I open and this got a different warning message......

![error 4](https://user-images.githubusercontent.com/115413953/194764737-06d323c2-ab90-43f4-bd8f-c25c487dc9ed.JPG)
![error 5](https://user-images.githubusercontent.com/115413953/194765642-5dab2e47-cb5a-41b2-a60b-49a81544d8b4.JPG)
![error 2](https://user-images.githubusercontent.com/115413953/194764740-760455dd-f478-4d38-b750-d51258d41384.JPG)
![error 1](https://user-images.githubusercontent.com/115413953/194764743-5c883a11-1999-427c-a4b7-dd4cd60856ac.JPG)

**Comment by ojungleboy** [comment]
Hello, I am having the same trouble.

Does anyone know how to solve it?
I am trying to use a 4067 with ESP32, The baud rate is matching to the Hairless serial but it seems that the MIDI messages are coming with garbage
![image](https://github.com/RyoKosaka/HelloDrum-arduino-Library/assets/99152906/c3e51e25-aab1-48f3-9fcc-4ec3f136a892)
