### ISSUE TITLE
Tcrt 5000 IR Inverted 

### ISSUE THREAD

**Issue by yogarisnandar** [RyoKosaka/HelloDrum-arduino-Library#53]
hello , i'm new here , your code is working fine , but i've problem with pedal open / close , it reversed / inverted , 
when i open   : the pedal send on close position and vice versa, how to fix it ? thanks ,

i try example from hellodrum hihat, 

sorry my bad english , 
i;m indonesian 
thanks :)

the sensor :
![sn](https://user-images.githubusercontent.com/121898608/210431736-4bcd1e01-5034-46db-97a0-3292fe32ed54.jpg)

**Comment by JojoRamadhan** [comment]
just reverse threshold and sensitivity in the HIHAT_PEDAL setting value
